"use client";
import Link from "next/link";
import TopBar from "@/components/TopBar";
import {useEffect,useState} from "react";
export default function Wallet(){
 const[u,setU]=useState<any>(null),[loaded,setLoaded]=useState(false),[amount,setAmount]=useState(10),[e,setE]=useState(""),[loading,setLoading]=useState(false);
 useEffect(()=>{fetch("/api/me").then(r=>r.json()).then(d=>{setU(d.user);setLoaded(true)})},[]);
 async function topup(){setLoading(true);setE("");const d=await fetch("/api/payments/cryptomus/create",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({amount})}).then(r=>r.json());if(!d.ok)setE(d.error||"Unable to create payment");else location.href=d.url;setLoading(false)}
 return <div><TopBar title="Wallet"/>{loaded&&!u?<div className="auth-page"><div className="brand-mark">N</div><h1>Sign in to your wallet</h1><p>Your coin balance and payments are available after you sign in.</p><div className="form-card"><Link className="primary-btn full" href="/login">Sign in</Link><Link className="secondary-btn full" href="/signup">Create account</Link></div></div>:<><div className="wallet-hero"><span>AVAILABLE COINS</span><strong>{Number(u?.coins||0).toLocaleString()}</strong><small>1 USD = 100 coins</small></div><div className="section-head"><div><span className="eyebrow">CRYPTO PAYMENT</span><h2>Add coins</h2></div></div><div className="topup-grid">{[5,10,25,50].map(x=><button key={x} className="coin-pack" onClick={()=>setAmount(x)}><b>{x}$</b><small>{x*100} coins</small></button>)}</div><div className="form-card"><label>Amount in USD<input value={amount} onChange={e=>setAmount(Number(e.target.value))} type="number" min="1"/></label>{e&&<div className="error-box">{e}</div>}<button className="primary-btn full" onClick={topup} disabled={loading}>{loading?"Creating invoice…":"Pay with Crypto"}</button><p className="tiny-note">Coins are credited only after Cryptomus confirms the payment.</p></div></>}</div>
}