import Link from "next/link";
export default function MobileAppsPage(){return <div style={{paddingBottom:40}}>
<div style={{padding:"34px 20px 20px"}}><Link href="/" style={{color:"#72dfce",fontWeight:800}}>← Numelixa</Link><span className="eyebrow" style={{display:"block",marginTop:30}}>NUMELIXA MOBILE</span><h1 style={{fontSize:"clamp(38px,9vw,58px)",letterSpacing:"-2.5px",margin:"8px 0"}}>Your account.<br/>Built for mobile.</h1><p style={{maxWidth:620,color:"var(--muted)",fontSize:15,lineHeight:1.7}}>Get the official Numelixa mobile experience with your wallet, numbers, verification codes, live status and native notifications in one place.</p></div>
<section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(250px,1fr))",gap:14,padding:"10px 20px"}}>
<div className="form-card" style={{padding:24,position:"relative",overflow:"hidden"}}><div style={{fontSize:44}}>🤖</div><span className="eyebrow">ANDROID</span><h2 style={{fontSize:27,margin:"7px 0"}}>Numelixa for Android</h2><p style={{color:"var(--muted)",lineHeight:1.6,fontSize:13}}>Native APK with push notifications, background update downloads and the complete Numelixa account experience.</p><div style={{display:"flex",gap:8,flexWrap:"wrap",margin:"16px 0"}}>{["Native app","Push alerts","Auto updates","Android 8+"] .map(x=><span key={x} style={{fontSize:11,padding:"6px 9px",borderRadius:999,background:"rgba(114,223,206,.08)",color:"#86ddd0"}}>{x}</span>)}</div><a href="https://numelixa.com/api/mobile/apk" className="primary-btn full" style={{boxSizing:"border-box"}}>Download Android APK <span>↓</span></a><small style={{display:"block",marginTop:10,color:"var(--muted)"}}>Official package: com.numelixa.app</small></div>
<div className="form-card" style={{padding:24,opacity:.88,position:"relative"}}><div style={{fontSize:44}}></div><span className="eyebrow">IOS</span><h2 style={{fontSize:27,margin:"7px 0"}}>Numelixa for iPhone</h2><p style={{color:"var(--muted)",lineHeight:1.6,fontSize:13}}>The iOS version is being prepared with the same account, wallet and notification experience.</p><div style={{margin:"25px 0",padding:"13px 14px",borderRadius:14,background:"rgba(255,255,255,.035)",border:"1px solid rgba(255,255,255,.08)",fontWeight:900}}>COMING SOON</div><button className="secondary-btn full" disabled style={{opacity:.65}}>iOS App · Coming Soon</button></div>
</section>
<section style={{padding:"28px 20px"}}><div className="eyebrow">WHY THE APP</div><div className="quick-grid" style={{marginTop:12}}><div className="quick-card"><span>◉</span><div><b>Real push notifications</b><small>Order, SMS code and account alerts.</small></div></div><div className="quick-card"><span>↻</span><div><b>Safe updates</b><small>See exact APK size and download progress.</small></div></div><div className="quick-card"><span>◈</span><div><b>One account</b><small>Your wallet and orders stay synced.</small></div></div></div></section>
</div>}
