import type {Metadata} from "next";
import Link from "next/link";
export const metadata:Metadata={title:"Privacy Policy",description:"Privacy information for Numelixa users.",alternates:{canonical:"https://numelixa.com/privacy/"}};
export default function PrivacyPage(){return <main className="public-doc-page"><Link href="/" className="public-doc-brand"><span>N</span><b>Numelixa</b></Link><span className="eyebrow">NUMELIXA PRIVACY · VERSION 2026-10-10</span><h1>Privacy Policy</h1><p>This page summarizes categories of information used by the current service. The owner should verify actual retention periods, hosting locations, legal basis and request procedures before treating this policy as a complete legal statement.</p>
<section className="public-doc-section"><h2>1. Information handled</h2><p>Depending on the features you use, Numelixa may process your name, email address, authentication and verification records, account settings, orders, number status, wallet and transaction records, API activity, support requests and device push token used for app notifications.</p></section>
<section className="public-doc-section"><h2>2. How information is used</h2><p>Information is used to authenticate accounts, provide virtual-number and SMS functionality, process orders and wallet operations, prevent abuse, protect sessions, deliver notifications, troubleshoot failures and respond to support requests.</p></section>
<section className="public-doc-section"><h2>3. Providers and sharing</h2><p>Some information must be processed by infrastructure, SMS/number providers, payment processors, email delivery providers and push-notification services to operate the requested features. The precise provider list and data transfer locations should be confirmed by the service owner. Numelixa does not ask users to put passwords or private payment credentials in support messages.</p></section>
<section className="public-doc-section"><h2>4. Payments</h2><p>Payment details may be handled by the selected payment provider. Numelixa uses provider and backend confirmations to determine payment status. The exact payment data retained by each provider is governed by that provider's terms and privacy policy.</p></section>
<section className="public-doc-section"><h2>5. Retention and security</h2><p>Account, order, security and transaction records may be retained as needed to operate the service, investigate abuse, resolve disputes and meet applicable obligations. Specific retention periods and technical safeguards vary by record type and must be confirmed by the owner. No system can guarantee absolute security.</p></section>
<section className="public-doc-section"><h2>6. Your choices and requests</h2><p>You can manage account and notification settings available in the app. API keys can be revoked where that feature is provided. For privacy questions or requests, email <a href="mailto:info@numelixa.com">info@numelixa.com</a>; applicable rights and verification steps depend on the law that applies to your situation.</p></section>
<section className="public-doc-section"><h2>7. Policy updates</h2><p>This policy may be updated when the service, providers or legal requirements change. The current version and effective date should be reviewed whenever the policy is changed.</p></section>
<section className="public-doc-section"><h2>Related pages</h2><p>Read the <Link href="/terms">Terms &amp; Conditions</Link> or visit <Link href="/support">Help &amp; Support</Link>.</p></section></main>}
