"use client";
import {useEffect,useState} from "react";
type Ticket={id:string;userId:string;userEmail:string;userName:string;channel:string;contact:string;subject:string;message:string;status:string;createdAt:string;reviewUntil:string};
export default function AdminSupport(){
 const [tickets,setTickets]=useState<Ticket[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState("");
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/admin/support",{cache:"no-store"}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Unable to load support requests.");setTickets(d.tickets||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load support requests.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function setStatus(id:string,status:string){setBusy(id);setError("");try{const r=await fetch("/api/admin/support",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Unable to update request.");setTickets(old=>old.map(t=>t.id===id?{...t,status}:t))}catch(e){setError(e instanceof Error?e.message:"Unable to update request.")}finally{setBusy("")}}
 return <section className="admin-card admin-support"><div className="admin-support-heading"><div><h2>Support inbox</h2><p>Customer requests and preferred reply channels</p></div><button className="secondary-btn" onClick={()=>void load()} disabled={loading}>Refresh</button></div>
 {error&&<div className="error-box">{error}</div>}{loading?<p>Loading support requests…</p>:!tickets.length?<p>No support requests have been submitted yet.</p>:tickets.map(t=><article className="admin-support-ticket" key={t.id}><div className="admin-support-ticket-head"><div><b>{t.subject}</b><small>{t.userName||"User"} · {t.userEmail} · {new Date(t.createdAt).toLocaleString()}</small></div><span className={"status "+(t.status==="resolved"?"active":"")}>{t.status}</span></div><p>{t.message}</p><div className="admin-support-contact"><span><b>Reply via:</b> {t.channel}</span><span><b>Contact:</b> {t.contact}</span><button className="secondary-btn" onClick={()=>void navigator.clipboard?.writeText(t.contact)}>Copy contact</button></div><div className="admin-support-actions">{(["reviewing","resolved","rejected"] as const).map(s=><button key={s} disabled={busy===t.id||t.status===s} className={t.status===s?"primary-btn":"secondary-btn"} onClick={()=>void setStatus(t.id,s)}>{s==="reviewing"?"In review":s==="resolved"?"Mark resolved":"Reject"}</button>)}</div></article>)}</section>
}
