"use client";
import {useEffect,useState} from "react";
type Sent={id:string;title:string;message:string;target:string;createdAt:string;sentCount:number};
export default function AdminNotifications(){
 const[title,setTitle]=useState(""),[message,setMessage]=useState(""),[target,setTarget]=useState("all"),[users,setUsers]=useState<{id:string;name:string;email:string}[]>([]),[history,setHistory]=useState<Sent[]>([]),[busy,setBusy]=useState(false),[result,setResult]=useState("");
 async function load(){try{const r=await fetch("/api/admin/notifications",{cache:"no-store"});const d=await r.json();if(d.ok)setHistory(d.notifications||[])}catch{}}
 useEffect(()=>{load();fetch("/api/admin/users",{cache:"no-store"}).then(r=>r.json()).then(d=>{if(d.ok)setUsers(d.users||[])}).catch(()=>{})},[]);
 async function send(e:React.FormEvent){e.preventDefault();setBusy(true);setResult("");try{const r=await fetch("/api/admin/notifications",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title,message,target})});const d=await r.json();if(!d.ok){setResult(d.error||"Unable to send");return}setResult("Sent to "+d.recipients+" users · "+d.sent+" push devices");setTitle("");setMessage("");load()}finally{setBusy(false)}}
 return <div className="admin-notifications"><div className="notification-compose"><span className="eyebrow">PUSH CENTER</span><h2>Send a notification</h2><p>Send an important update to every user or one specific user. Messages are also saved inside the app notification center.</p><form onSubmit={send} className="admin-form"><label>Audience<select value={target} onChange={e=>setTarget(e.target.value)}><option value="all">All users</option>{users.map(u=><option key={u.id} value={"user:"+u.id}>{u.name||"Unnamed"} · {u.email}</option>)}</select></label><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={80} placeholder="e.g. New Numelixa update"/></label><label>Message<textarea value={message} onChange={e=>setMessage(e.target.value)} maxLength={500} rows={5} placeholder="Write the notification…"/></label><button className="primary-btn" disabled={busy||!title.trim()||!message.trim()}>{busy?"Sending…":"🔔 Send notification"}</button>{result&&<div className="success-box">{result}</div>}</form></div><Table title={"Recent notifications ("+history.length+")"}>{history.length?history.map(x=><div className="admin-notification-history" key={x.id}><div><b>{x.title}</b><p>{x.message}</p><small>{new Date(x.createdAt).toLocaleString()} · {x.sentCount||0} push sent</small></div></div>):<div className="country-loading">No notifications sent yet.</div>}</Table></div>
}
function Table({title,children}:{title:string;children:React.ReactNode}){return <div className="admin-card"><h2>{title}</h2>{children}</div>}
