"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
type Stats={users:number;activeNumbers:number;todayOrders:number;revenueCoins:number;providers:{name:string;status:string}[]};
export default function AdminPanel(){const[stats,setStats]=useState<Stats|null>(null);const[tab,setTab]=useState("overview");useEffect(()=>{fetch("/api/admin/stats").then(r=>r.json()).then(setStats)},[]);return <div className="admin-shell"><header className="admin-header"><div><span className="eyebrow">NUMELIXA ADMIN</span><h1>Control center</h1></div><Link href="/" className="secondary-btn">Open app</Link></header><div className="admin-tabs">{["overview","users","orders","pricing","providers","settings"].map(x=><button key={x} className={tab===x?"tab active":"tab"} onClick={()=>setTab(x)}>{x}</button>)}</div>{tab==="overview"&&<Overview stats={stats}/>} {tab==="users"&&<AdminList title="Users" rows={["@mohamed · 1,240 coins","@abdullahi · 420 coins","@testuser · 90 coins","@business · 8,900 coins"]}/>} {tab==="orders"&&<AdminList title="Recent orders" rows={["WhatsApp · +1 202… · active","Telegram · +44 7… · waiting","TikTok · +49 15… · received","Google · +1 202… · active"]}/>} {tab==="pricing"&&<Pricing/>} {tab==="providers"&&<Providers stats={stats}/>} {tab==="settings"&&<Settings/>}</div>}
function Overview({stats}:{stats:Stats|null}){const cards=[["Users",stats?.users??"—","registered"],["Active numbers",stats?.activeNumbers??"—","live"],["Today's orders",stats?.todayOrders??"—","orders"],["Revenue",stats?stats.revenueCoins.toLocaleString():"—","coins"]];return <><div className="admin-grid">{cards.map(([a,b,c])=><div className="metric" key={a}><span>{a}</span><strong>{b}</strong><small>{c}</small></div>)}</div><div className="admin-card"><h2>System checklist</h2>{["User and wallet UI","Service/country catalog","Number → code flow","Admin controls","Production database + payments"].map((x,i)=><div className="check" key={x}><span>{i===4?"•":"✓"}</span> {x}</div>)}</div></>}
function AdminList({title,rows}:{title:string;rows:string[]}){return <div className="admin-card"><h2>{title}</h2>{rows.map(row=><div className="admin-row" key={row}><span>{row}</span><button>Manage</button></div>)}</div>}
function Pricing(){return <div className="admin-card"><h2>Pricing rules</h2>{["WhatsApp · US · 20 coins","Telegram · UK · 18 coins","TikTok · DE · 22 coins","Google · US · 30 coins"].map(x=><div className="admin-row" key={x}><span>{x}</span><button>Edit</button></div>)}<button className="primary-btn full">+ Add pricing rule</button></div>}
function Providers({stats}:{stats:Stats|null}){return <div className="admin-card"><h2>Providers</h2>{stats?.providers.map(p=><div className="admin-row" key={p.name}><span><b>{p.name}</b><small>{p.status}</small></span><button>Configure</button></div>)}<div className="notice"><span>!</span><p>Keep provider API keys in Vercel Environment Variables. Never commit secrets to GitHub.</p></div></div>}
function Settings(){return <div className="admin-card"><h2>Platform settings</h2><label>App name<input defaultValue="Numelixa"/></label><label>Default currency<input defaultValue="Coins"/></label><label>Order timeout<input defaultValue="10 minutes"/></label><button className="primary-btn full">Save settings</button></div>}
