"use client";import type {FormEvent,ReactNode} from "react";import {useEffect,useState} from "react";import Link from "next/link";
type Stats={users:number;activeNumbers:number;todayOrders:number;revenueCoins:number;settings:{markupPercent:number;coinsPerUsd:number;minTopupUsd:number;maxTopupUsd:number};providers:{name:string;status:string;balance?:any}[]};
export default function AdminPanel(){const[stats,setStats]=useState<Stats|null>(null),[tab,setTab]=useState("overview"),[rows,setRows]=useState<any[]>([]),[error,setError]=useState(""),[saved,setSaved]=useState("");
async function load(){const r=await fetch("/api/admin/stats"),d=await r.json();d.ok?setStats(d):setError(d.error||"Unable to load admin data")}useEffect(()=>{load()},[]);
useEffect(()=>{if(tab==="users"||tab==="orders"){fetch("/api/admin/"+tab).then(r=>r.json()).then(d=>d.ok?setRows(d[tab]||[]):setError(d.error||"Unauthorized"))}},[tab]);
async function saveSettings(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!stats)return;const f=new FormData(e.currentTarget),body={markupPercent:Number(f.get("markupPercent")),coinsPerUsd:Number(f.get("coinsPerUsd")),minTopupUsd:Number(f.get("minTopupUsd")),maxTopupUsd:Number(f.get("maxTopupUsd"))};const r=await fetch("/api/admin/stats",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),d=await r.json();if(d.ok){setStats({...stats,settings:d.settings});setSaved("Settings saved.");setTimeout(()=>setSaved(""),2500)}else setError(d.error||"Unable to save")}
return <div className="admin-shell"><header className="admin-header"><div><span className="eyebrow">NUMELIXA ADMIN</span><h1>Control center</h1></div><Link href="/" className="secondary-btn">Open app</Link></header>{error&&<div className="error-box">{error}</div>}{saved&&<div className="success-box">{saved}</div>}<div className="admin-tabs">{["overview","users","orders","providers","pricing"].map(x=><button key={x} className={tab===x?"tab active":"tab"} onClick={()=>setTab(x)}>{x}</button>)}</div>
{tab==="overview"&&<Overview stats={stats}/>} {tab==="users"&&<Table title="Users">{rows.map(x=><div className="admin-row" key={x.id}><span><b>{x.name}</b><small>{x.email} · {Number(x.coins).toLocaleString()} coins</small></span><small>{x.role}</small></div>)}</Table>}
{tab==="orders"&&<Table title="All orders">{rows.map(x=><div className="admin-row" key={x.id}><span><b>{x.service} · {x.phone_number||"pending"}</b><small>{x.country} · {x.email}</small></span><small>{x.status} · {Number(x.price_coins||0).toLocaleString()} coins</small></div>)}</Table>}
{tab==="providers"&&<Providers stats={stats}/>}
{tab==="pricing"&&stats&&<Table title="Numelixa pricing"><form onSubmit={saveSettings} className="admin-form"><label>Provider markup %<input name="markupPercent" type="number" min="0" step="0.1" defaultValue={stats.settings.markupPercent}/></label><label>Coins per $1 USD<input name="coinsPerUsd" type="number" min="1" step="1" defaultValue={stats.settings.coinsPerUsd}/></label><label>Minimum top-up USD<input name="minTopupUsd" type="number" min="0.01" step="0.01" defaultValue={stats.settings.minTopupUsd}/></label><label>Maximum top-up USD<input name="maxTopupUsd" type="number" min="0.01" step="0.01" defaultValue={stats.settings.maxTopupUsd}/></label><button className="primary-btn" type="submit">Save pricing</button></form><p className="helper-text">Every country price shown to users is calculated live from SMS-Activate cost + this markup, then converted to coins.</p></Table>}</div>}
function Overview({stats}:{stats:Stats|null}){return <><div className="admin-grid">{[["Users",stats?.users??"—"],["Active",stats?.activeNumbers??"—"],["Today",stats?.todayOrders??"—"],["Credits",stats?stats.revenueCoins.toLocaleString():"—"]].map(([a,b])=><div className="metric" key={a}><span>{a}</span><strong>{b}</strong><small>live database</small></div>)}</div><Table title="System health"><div className="check">✓ Persistent MongoDB data</div><div className="check">✓ Live SMS-Activate catalog, stock and orders</div><div className="check">✓ Cryptomus webhook wallet credits</div><div className="check">✓ Spacemail transactional email</div></Table></>}
function Table({title,children}:{title:string;children:ReactNode}){return <div className="admin-card"><h2>{title}</h2>{children}</div>}
function Providers({stats}:{stats:Stats|null}){return <Table title="Providers">{stats?.providers.map(p=><div className="admin-row" key={p.name}><span><b>{p.name}</b><small>{p.name==="SMS-Activate"&&p.balance!==undefined?`Provider balance: $${Number(p.balance).toFixed(2)}`:"Server-side integration"}</small></span><small>{p.status}</small></div>)}</Table>}
