"use client";import {useEffect,useState} from "react";
export default function CodeClient({orderId}:{orderId:string}){const[code,setCode]=useState(""),[status,setStatus]=useState("waiting"),[loading,setLoading]=useState(false),[seconds,setSeconds]=useState(600),[error,setError]=useState("");
async function getCode(){if(code||status==="refunded"||status==="cancelled")return;setLoading(true);try{const r=await fetch("/api/orders/code",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderId})}),d=await r.json();if(d.ok){setCode(d.code||"");setStatus(d.status||"waiting");if(d.timeLeft!=null)setSeconds(Number(d.timeLeft))}else{setStatus(d.status||"refunded");setError(d.error||"")} }finally{setLoading(false)}}
async function cancelOrder(){if(!confirm("Cancel this number? Your coins will be refunded if cancellation is accepted."))return;setLoading(true);setError("");try{const r=await fetch("/api/orders",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderId})}),d=await r.json();if(!d.ok)throw new Error(d.error||"Unable to cancel");setStatus("cancelled");setError("Order cancelled. Your coins were refunded.")}catch(e){setError(e instanceof Error?e.message:"Unable to cancel")}finally{setLoading(false)}}
useEffect(()=>{getCode();const t=setInterval(()=>{if(!code&&status==="waiting")getCode()},5000);return()=>clearInterval(t)},[orderId,code,status]);
useEffect(()=>{if(status!=="waiting")return;const t=setInterval(()=>setSeconds(s=>Math.max(0,s-1)),1000);return()=>clearInterval(t)},[status]);
async function copy(){if(code)await navigator.clipboard.writeText(code)}
const m=Math.floor(seconds/60),s=seconds%60;
return <div className="code-area">{code?<><div className="otp">{code}</div><button className="secondary-btn full" onClick={copy}>Copy code</button><span className="waiting-dot">● SMS received</span></>:status==="waiting"?<><button className="primary-btn full" onClick={getCode} disabled={loading}>{loading?"Checking SMS…":"Check for code"}</button><span className="waiting-dot">● Waiting for SMS · {m}:{String(s).padStart(2,"0")}</span>{seconds>300&&<button className="secondary-btn full" onClick={cancelOrder} disabled={loading}>Cancel & refund</button>}</>:<span className="waiting-dot">● {status}</span>}{error&&<div className={status==="cancelled"||status==="refunded"?"success-box":"error-box"}>{error}</div>}</div>}
