"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
type Props={service:string;country:string;countryName?:string};
type Stock={count:number;sellCoins:number;usdPrice:number;providerCost:number;coinsPerUsd:number;rate?:number;operator?:string};
const common:Record<string,string>={whatsapp:"WhatsApp",telegram:"Telegram",google:"Google",facebook:"Facebook",instagram:"Instagram/Threads",tiktok:"TikTok",twitter:"X / Twitter",x:"X",snapchat:"Snapchat",viber:"Viber",discord:"Discord",amazon:"Amazon",microsoft:"Microsoft",apple:"Apple",signal:"Signal",wechat:"WeChat",yahoo:"Yahoo",openai:"OpenAI/ChatGPT",claudeai:"Claude AI/Anthropic"};
function nameOf(s:string){return common[s.toLowerCase()]||s.replace(/[_-]+/g," ").replace(/\b\w/g,c=>c.toUpperCase())}
function friendlyError(value:string){const x=value.toLowerCase();if(x.includes("no free")||x.includes("no stock")||x.includes("out of stock"))return "No free Numbers";if(x.includes("not enough user balance")||x.includes("balance"))return "Service unavailable";if(x.includes("price_changed")||x.includes("price changed")||x.includes("maxprice"))return "Price changed";if(x.includes("bad country")||x.includes("bad operator")||x.includes("no product"))return "Service unavailable";if(x.includes("server offline")||x.includes("temporarily unavailable")||x.includes("timeout"))return "Service temporarily unavailable";if(x.includes("provider")||x.includes("5sim"))return "Unable to get number";return value.replace(/5SIM[^:]*:\s*/ig,"").trim()||"Unable to reserve a number."}
export default function GetNumberClient({service,country,countryName}:Props){
 const router=useRouter();const[loading,setLoading]=useState(false),[stock,setStock]=useState<Stock|null>(null),[checking,setChecking]=useState(true),[error,setError]=useState("");const name=nameOf(service),slug=service.toLowerCase();
 useEffect(()=>{fetch("/api/catalog/stock?country="+encodeURIComponent(country)+"&service="+encodeURIComponent(service),{cache:"no-store"}).then(r=>r.json()).then(d=>{if(d.ok)setStock({count:Number(d.stock.count||0),sellCoins:Number(d.stock.sellCoins||0),usdPrice:Number(d.stock.usdPrice||0),providerCost:Number(d.stock.providerCost||0),coinsPerUsd:Number(d.stock.coinsPerUsd||0),rate:Number(d.stock.rate||0),operator:String(d.stock.operator||"any")})}).catch(()=>{}).finally(()=>setChecking(false))},[country,service]);
 async function getNumber(){setLoading(true);setError("");try{const r=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({service,country,countryCode:country,countryName:countryName||country})});const d=await r.json();if(r.status===401){router.push("/login?next="+encodeURIComponent("/get-code/new?service="+service+"&country="+country+"&countryName="+(countryName||country)));return}if(r.status===402){router.push("/wallet");return}if(r.status===403&&d.code==="EMAIL_VERIFICATION_REQUIRED"){router.push("/verify-email");return}if(!d.ok)throw new Error(friendlyError(d.error||"Unable to reserve a number."));router.push("/get-code/"+d.order.id)}catch(e){setError(friendlyError(e instanceof Error?e.message:"Unable to reserve a number."))}finally{setLoading(false)}}
 return <div className="get-number-wrap"><div className="code-card get-number-card"><span className={"service-badge service-icon-"+slug}><img src={"https://cdn.simpleicons.org/"+slug} alt="" onError={e=>{e.currentTarget.style.display="none"}}/><span className="service-fallback">{name.slice(0,1)}</span></span><h1>{name}</h1><p>{countryName||country}</p><div className="availability-panel"><div><small>Available numbers</small><strong>{checking?"…":stock?stock.count.toLocaleString():"—"}</strong></div><div><small>Price per number</small><strong>{stock?"$"+stock.usdPrice.toFixed(2):"—"}</strong><em>{stock?stock.sellCoins.toLocaleString()+" coins":""}</em></div></div>{stock?<div className="purchase-line"><span>Provider price</span><b>{"$"+stock.providerCost.toFixed(2)}</b></div>:null}{stock?<div className="purchase-line"><span>Operator</span><b>{stock.operator==="any"?"Any":stock.operator}</b></div>:null}{stock?.rate?<div className="purchase-line"><span>Delivery rate</span><b>{stock.rate.toFixed(0)+"%"}</b></div>:null}<div className="purchase-line"><span>Delivery</span><b>Instant</b></div><div className="purchase-line"><span>SMS window</span><b>Up to 5 minutes</b></div>{error&&<div className="error-box">{error}</div>}<button className="primary-btn full" onClick={getNumber} disabled={loading||!stock||stock.count<1}>{loading?"Reserving…":"Get Number  →"}</button><div className="purchase-hints"><span>↻ Refund if no SMS</span><span>◈ Cancel when available</span></div></div></div>;
}