"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {Capacitor} from "@capacitor/core";
type TopBarProps={title?:string;back?:boolean};type MeResponse={ok?:boolean;user?:{coins?:number;name?:string;email?:string}|null};
export default function TopBar({title="Numelixa",back=false}:TopBarProps){
 const[open,setOpen]=useState(false),[coins,setCoins]=useState<number|null>(null),[native,setNative]=useState(false),[initial,setInitial]=useState("N");
 useEffect(()=>{setNative(Capacitor.isNativePlatform());let cancelled=false;fetch("/api/me",{cache:"no-store"}).then(async r=>r.ok?(await r.json()) as MeResponse:null).then(d=>{if(!cancelled&&d?.user){setCoins(Number(d.user.coins||0));setInitial(String(d.user.name||d.user.email||"N").trim().charAt(0).toUpperCase()||"N");window.dispatchEvent(new Event("numelixa-auth-ready"))}}).catch(()=>{if(!cancelled)setCoins(null)});return()=>{cancelled=true}},[]);
 return <header className={"topbar "+(back?"topbar-detail":"topbar-brand")}><div className="topbar-inner">
  {back?<Link href="/" className="icon-btn" aria-label="Back"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.1"><path d="M15 18l-6-6 6-6"/></svg></Link>:<Link href="/" className="brand-lockup" aria-label="Numelixa home"><span className="brand-logo">N</span><span className="brand-copy"><b>Numelixa</b><small>Virtual Numbers · Global SMS</small></span></Link>}
  <div className="top-title">{back?title:""}</div>
  <div className="topbar-actions">{coins!==null?<Link href="/wallet" className="coin-pill" aria-label={"Wallet balance: "+coins.toLocaleString()+" coins"}><span className="coin-icon" aria-hidden="true">🪙</span><span>{coins.toLocaleString()}</span><small>coins</small></Link>:null}
{back?<button className="icon-btn" type="button" aria-label="Filters" onClick={()=>document.getElementById("country-filters")?.scrollIntoView({behavior:"smooth",block:"center"})}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M4 7h10M18 7h2M4 12h2M10 12h10M4 17h10M18 17h2"/><circle cx="16" cy="7" r="2"/><circle cx="8" cy="12" r="2"/><circle cx="16" cy="17" r="2"/></svg></button>:<button className="icon-btn home-menu-btn account-avatar-trigger" type="button" aria-label="Open account menu" aria-expanded={open} onClick={()=>setOpen(v=>!v)}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="12" cy="8" r="3.5"/><path d="M5 20a7 7 0 0 1 14 0"/></svg><span className="topbar-avatar-initial">{initial}</span></button>}</div>
 </div>
 {!back&&open?<div className="top-menu"><Link href="/" onClick={()=>setOpen(false)}>Home</Link><Link href="/services" onClick={()=>setOpen(false)}>Get a number</Link><Link href="/numbers" onClick={()=>setOpen(false)}>My orders</Link><Link href="/wallet" onClick={()=>setOpen(false)}>Wallet</Link><Link href="/account" onClick={()=>setOpen(false)}>Account</Link><Link href="/support" onClick={()=>setOpen(false)}>Support</Link><Link href="/developers" onClick={()=>setOpen(false)}>Developer API</Link>{!native&&<><Link href="/android" onClick={()=>setOpen(false)}>📱 Android App</Link><Link href="/ios" onClick={()=>setOpen(false)}> iOS App</Link></>}</div>:null}
 </header>
}