"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";

export default function VerifyEmailClient(){
 const router=useRouter();
 const[code,setCode]=useState("");const[loading,setLoading]=useState(false);const[sending,setSending]=useState(false);const[message,setMessage]=useState("");const[error,setError]=useState("");const[verified,setVerified]=useState(false);
 useEffect(()=>{sendCode()},[]);
 async function sendCode(){setSending(true);setError("");setMessage("");try{const r=await fetch("/api/auth/verification/start",{method:"POST"}),d=await r.json();if(!d.ok)throw new Error(d.error||"Unable to send verification code.");if(d.verified){setVerified(true);setMessage("Your email is already verified.");return}setMessage("Code sent");}catch(e){setError(e instanceof Error?e.message:"Unable to send verification code.")}finally{setSending(false)}}
 async function confirm(){setLoading(true);setError("");setMessage("");try{const r=await fetch("/api/auth/verification/confirm",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code})}),d=await r.json();if(!d.ok)throw new Error(d.error||"Verification failed.");setVerified(true);setMessage("Email verified successfully.");setTimeout(()=>router.push("/account"),700)}catch(e){setError(e instanceof Error?e.message:"Verification failed.")}finally{setLoading(false)}}
 if(verified)return <div className="form-card"><div className="success-box">✓ Email verified successfully.</div><button className="primary-btn full" onClick={()=>router.push("/account")}>Continue</button></div>;
 return <div className="form-card"><span className="eyebrow">EMAIL VERIFICATION</span><h2>Verify your email</h2><p>Enter the 6-digit code sent to your email. Verification is required before you can purchase a number.</p><label>Verification code<input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} inputMode="numeric" autoComplete="one-time-code" placeholder="000000"/></label>{message&&<div className="auth-note" style={{margin:"4px 0 12px",padding:"9px 11px",borderRadius:12,background:"rgba(98,229,207,.07)",border:"1px solid rgba(98,229,207,.12)",color:"#78b8b3",textAlign:"left"}}>✓ A 6-digit code was sent to your email.</div>}{error&&<div className="error-box">{error}</div>}<button className="primary-btn full" style={{minHeight:46,marginTop:2}} onClick={confirm} disabled={loading||code.length!==6}>{loading?"Verifying…":"Verify email"}</button><button className="secondary-btn full" style={{minHeight:42,marginTop:8}} onClick={sendCode} disabled={sending}>{sending?"Sending…":"Resend code"}</button></div>;
}
