import type {Metadata} from "next";
import Link from "next/link";
export const metadata:Metadata={title:"Terms & Conditions",description:"Terms and conditions for using Numelixa."};
export default function TermsPage(){return <main className="public-doc-page"><Link href="/" className="public-doc-brand"><span>N</span><b>Numelixa</b></Link><span className="eyebrow">NUMELIXA LEGAL · VERSION 2026-10-10</span><h1>Terms &amp; Conditions</h1><p><b>Important:</b> These terms describe general platform rules. The owner should review them against the actual refund policy, business jurisdiction and applicable law before treating them as final legal advice.</p>
<section className="public-doc-section"><h2>1. Acceptance</h2><p>By creating or using a Numelixa account, website, API or application, you agree to these Terms &amp; Conditions and acknowledge the <Link href="/privacy">Privacy Policy</Link>.</p></section>
<section className="public-doc-section"><h2>2. Accounts and security</h2><p>Provide accurate account information, protect your password and API keys, and promptly report suspected unauthorized access. You are responsible for activity performed through your account, subject to applicable law and platform security processes.</p></section>
<section className="public-doc-section"><h2>3. Virtual number services</h2><p>Numbers are offered for supported services only and depend on third-party provider inventory, carrier availability and service rules. A number, country, service or SMS delivery may become unavailable or delayed. Follow the conditions shown for the specific offer before purchasing.</p></section>
<section className="public-doc-section"><h2>4. Prices, wallet and payments</h2><p>Prices and inventory may change before an order is confirmed. Wallet credits and payment status are managed by the platform backend. A payment is considered completed only when confirmed by the relevant provider and platform. Do not rely on screenshots or browser messages as proof of payment.</p></section>
<section className="public-doc-section"><h2>5. Cancellations and refunds</h2><p>Refund eligibility depends on the actual order state, provider response and refund rules presented by Numelixa. Review the applicable refund information before purchasing. No additional refund promise is made by this general section.</p></section>
<section className="public-doc-section"><h2>6. Acceptable use</h2><p>You must not use Numelixa for fraud, phishing, credential theft, harassment, spam, unlawful activity, or to evade another service's security controls, usage rules or restrictions. You must comply with applicable laws and the rules of the service where you use a number.</p></section>
<section className="public-doc-section"><h2>7. Third-party providers and availability</h2><p>Numelixa relies on third-party infrastructure, payment processors, SMS providers and mobile networks. Interruptions, changes in inventory and delivery delays may occur. The platform does not promise uninterrupted availability.</p></section>
<section className="public-doc-section"><h2>8. Suspension and termination</h2><p>Access may be limited or suspended where reasonably necessary to protect users, investigate abuse, secure the platform, comply with provider rules or respond to legal requirements.</p></section>
<section className="public-doc-section"><h2>9. Changes and disputes</h2><p>Terms may be updated as the service changes. The owner must specify and review the applicable governing law, jurisdiction and dispute process before final publication; none is asserted here.</p></section>
<section className="public-doc-section"><h2>10. Contact</h2><p>For support questions, email <a href="mailto:info@numelixa.com">info@numelixa.com</a>.</p></section></main>}
