import nodemailer from "nodemailer";

const DEFAULT_HOST="mail.privateemail.com";
const DEFAULT_PORT=465;
type SmtpConfig={host:string;port:number;user:string;pass:string;from:string};

function smtpConfig():SmtpConfig{
 const host=(process.env.PRIVATE_EMAIL_SMTP_HOST||DEFAULT_HOST).trim();
 const port=Number(process.env.PRIVATE_EMAIL_SMTP_PORT||DEFAULT_PORT);
 const user=(process.env.PRIVATE_EMAIL_SMTP_USER||"info@numelixa.com").trim();
 const pass=process.env.PRIVATE_EMAIL_SMTP_PASSWORD||"";
 const from=(process.env.PRIVATE_EMAIL_FROM||user).trim();
 if(!user)throw new Error("Private Email SMTP username is missing.");
 if(!pass)throw new Error("Private Email SMTP password is missing.");
 if(!Number.isFinite(port)||port<=0||port>65535)throw new Error("Invalid Private Email SMTP port.");
 if(!from||!from.includes("@"))throw new Error("Spacemail sender address is missing or invalid.");
 return{host,port,user,pass,from};
}
function plain(html:string){return html.replace(/<style[^>]*>[\s\S]*?<\/style>/gi,"").replace(/<br\s*\/?>(?=.)/gi,"\n").replace(/<\/(p|div|h1|h2|h3|li)>/gi,"\n").replace(/<[^>]+>/g,"").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/\n{3,}/g,"\n\n").trim();}
function makeTransporter(config:SmtpConfig){const key="__numelixa_mailer_"+config.host+"_"+config.port+"_"+config.user;
 const g=globalThis as any;
 if(g[key])return g[key];
 const transporter=nodemailer.createTransport({host:config.host,port:config.port,secure:config.port===465,requireTLS:config.port===587,auth:{user:config.user,pass:config.pass},tls:{minVersion:"TLSv1.2",servername:config.host},connectionTimeout:8000,greetingTimeout:8000,socketTimeout:12000,pool:true,maxConnections:3,maxMessages:50} as any);
 g[key]=transporter;
 return transporter;}
async function sendWithConfig(config:SmtpConfig,to:string,subject:string,html:string){const transporter=makeTransporter(config);const domain=config.from.split("@")[1];await transporter.sendMail({from:"Numelixa <"+config.from+">",to,replyTo:config.from,subject,text:plain(html),html,messageId:"<numelixa-"+Date.now()+"-"+Math.random().toString(36).slice(2,10)+"@"+domain+">",date:new Date(),headers:{"X-Mailer":"Numelixa Transactional Mail","X-Application":"Numelixa","Auto-Submitted":"auto-generated"}});}
function isSocketTlsError(error:unknown){const e=error as {code?:unknown;message?:unknown}|null;const code=String(e?.code||"");const message=String(e?.message||"").toLowerCase();return["ESOCKET","ECONNRESET","ETIMEDOUT","EPIPE","ECONNREFUSED"].includes(code)||message.includes("secure tls")||message.includes("network socket disconnected")||message.includes("socket disconnected");}
export async function sendEmail(to:string,subject:string,html:string){const config=smtpConfig();try{await sendWithConfig(config,to,subject,html);}catch(error){if(config.port===465&&isSocketTlsError(error)){try{await sendWithConfig({...config,port:587},to,subject,html);return;}catch(fallbackError){const message=fallbackError instanceof Error?fallbackError.message:String(fallbackError);throw new Error("Private Email SMTP error: "+message);}}const message=error instanceof Error?error.message:String(error);throw new Error("Private Email SMTP error: "+message);}}

const shell=(content:string,preheader:string)=>{
 const logo='<table role="presentation" cellpadding="0" cellspacing="0" border="0" align="center" style="margin:0 auto"><tr><td align="center" valign="middle" style="width:46px;height:46px;border-radius:15px;background:linear-gradient(135deg,#58e6cf,#0c777a);color:#031d25;font-family:Arial,Helvetica,sans-serif;font-size:22px;font-weight:900;line-height:46px;text-align:center;vertical-align:middle;box-shadow:0 10px 28px rgba(39,218,190,.25)">N</td></tr></table>';
 return '<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"></head><body style="margin:0;background:#061d24;font-family:Arial,Helvetica,sans-serif;color:#ecfffb"><div style="display:none;max-height:0;overflow:hidden;opacity:0">'+preheader+'</div><div style="padding:34px 14px;background:radial-gradient(circle at 50% 0,#0b5960 0,#061d24 46%,#04151b 100%);min-height:100vh"><div style="max-width:590px;margin:auto"><div style="padding:4px 8px 18px">'+logo+'<div style="margin-top:10px;font-size:11px;font-weight:800;letter-spacing:3px;color:#78dccc">NUMELIXA</div></div><div style="background:rgba(7,40,48,.96);border:1px solid rgba(116,235,214,.16);border-radius:28px;padding:30px 26px;box-shadow:0 24px 70px rgba(0,0,0,.3)">'+content+'</div><div style="padding:22px 8px;text-align:center;color:#62898c;font-size:11px;line-height:1.6">Numelixa · Global Virtual Numbers<br>Secure account & SMS services</div></div></div></body></html>';
};

export function verificationEmail(code:string){
 return shell('<div style="font-size:10px;font-weight:900;letter-spacing:2.2px;color:#62ddca">EMAIL VERIFICATION</div><h1 style="font-size:31px;line-height:1.1;margin:10px 0;color:#f2fffc">Verify your email</h1><p style="font-size:14px;line-height:1.7;color:#a9ccca">Use the secure code below to confirm your Numelixa account.</p><div style="margin:22px 0;padding:22px;border-radius:20px;background:#041d25;border:1px solid rgba(100,235,211,.18);text-align:center"><div style="font-size:36px;letter-spacing:8px;font-weight:900;color:#f2fffc">'+code+'</div><div style="margin-top:8px;font-size:10px;color:#6e999a">Expires in 10 minutes</div></div><p style="font-size:11px;color:#709294;line-height:1.6">Never share this code. If you did not request it, you can safely ignore this email.</p>','Your Numelixa email verification code expires in 10 minutes.');
}
export function welcomeEmail(name:string){
 return shell('<div style="font-size:11px;font-weight:800;letter-spacing:2px;color:#62ddca">WELCOME TO NUMELIXA</div><h1 style="font-size:31px;line-height:1.1;margin:10px 0;color:#f2fffc">Welcome, '+escapeHtml(name)+' 👋</h1><p style="font-size:14px;line-height:1.7;color:#a9ccca">Your account is ready. You can now manage your wallet, virtual numbers and SMS codes from one clean dashboard.</p><div style="margin:24px 0;padding:18px;border-radius:18px;background:linear-gradient(135deg,rgba(48,187,167,.14),rgba(10,72,79,.35));border:1px solid rgba(100,235,211,.13)"><b style="font-size:14px;color:#dffff8">Your Numelixa journey starts here.</b><p style="font-size:12px;color:#82a8a8;line-height:1.6;margin:7px 0 0">Choose a service → choose a country → get your number → receive your SMS.</p></div>','Welcome to Numelixa — your account is ready.');
}
export function passwordResetEmail(name:string,url:string){
 return shell('<div style="font-size:11px;font-weight:800;letter-spacing:2px;color:#62ddca">ACCOUNT SECURITY</div><h1 style="font-size:31px;line-height:1.1;margin:10px 0;color:#f2fffc">Reset your password</h1><p style="font-size:14px;line-height:1.7;color:#a9ccca">Hi '+escapeHtml(name||"there")+', we received a request to reset your Numelixa password.</p><p><a href="'+url+'" style="display:inline-block;background:linear-gradient(135deg,#62e5cf,#2bbda9);color:#032027;padding:14px 22px;border-radius:14px;text-decoration:none;font-weight:900;font-size:13px">Reset password →</a></p><div style="margin-top:20px;padding:14px;border-radius:14px;background:#041d25;color:#789c9d;font-size:11px;line-height:1.6">This link expires in 30 minutes. If you did not request a password reset, no action is required.</div>','Secure Numelixa password reset link — expires in 30 minutes.');
}
export function purchaseSuccessEmail(name:string,service:string,country:string,number:string,price:number,url:string){
 return shell('<div style="font-size:11px;font-weight:800;letter-spacing:2px;color:#62ddca">PURCHASE COMPLETE</div><h1 style="font-size:31px;line-height:1.1;margin:10px 0;color:#f2fffc">Number secured 🎉</h1><p style="font-size:14px;line-height:1.7;color:#a9ccca">Hi '+escapeHtml(name||"there")+', congratulations! Your Numelixa number was purchased successfully.</p><div style="margin:24px 0;padding:20px;border-radius:20px;background:#041d25;border:1px solid rgba(100,235,211,.18)"><div style="font-size:10px;color:#679596;letter-spacing:1.5px;font-weight:800">SERVICE</div><div style="font-size:18px;font-weight:900;margin:5px 0 15px;color:#edfffb">'+escapeHtml(service)+'</div><div style="font-size:10px;color:#679596;letter-spacing:1.5px;font-weight:800">NUMBER</div><div style="font-size:24px;font-weight:900;margin-top:5px;color:#62e5cf">'+escapeHtml(number)+'</div><div style="font-size:11px;color:#789c9d;margin-top:10px">'+escapeHtml(country)+' · '+Number(price||0).toLocaleString()+" coins"+'</div></div><p><a href="'+url+'" style="display:inline-block;background:linear-gradient(135deg,#62e5cf,#2bbda9);color:#032027;padding:14px 22px;border-radius:14px;text-decoration:none;font-weight:900;font-size:13px">Open SMS & Get Code →</a></p>','Congratulations — your Numelixa number purchase was successful.');
}
function escapeHtml(value:string){return String(value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");}
export function emailTemplate(title:string,text:string,url?:string,preheader="Numelixa account security"){return shell('<h1 style="font-size:27px;color:#f2fffc">'+title+'</h1><p style="font-size:14px;line-height:1.7;color:#a9ccca">'+text+'</p>'+(url?'<p><a href="'+url+'" style="display:inline-block;background:linear-gradient(135deg,#62e5cf,#2bbda9);color:#032027;padding:14px 22px;border-radius:14px;text-decoration:none;font-weight:900">Continue to Numelixa →</a></p>':'') ,' '+preheader);}
