"use client";
import {useEffect,useState} from "react";import Link from "next/link";import {useRouter} from "next/navigation";import {Capacitor} from "@capacitor/core";import PhoneAuth from "@/components/PhoneAuth";import GoogleSignIn from "@/components/GoogleSignIn";
export default function Login(){
 const[email,setEmail]=useState(""),[secret,setSecret]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false),[next,setNext]=useState(""),[approval,setApproval]=useState<any>(null),[method,setMethod]=useState<"email"|"phone">("email"),router=useRouter();
 useEffect(()=>{setNext(new URLSearchParams(window.location.search).get("next")||"")},[]);
 async function go(){
  setError("");if(!email.trim()||!secret){setError("Enter your email and password.");return}setLoading(true);
  try{const d=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json","X-Numelixa-Client":Capacitor.isNativePlatform()?"android-app":"browser"},credentials:"include",body:JSON.stringify({email,password:secret})}).then(x=>x.json());
   if(d.approvalRequired){setApproval(d);return}if(!d.ok){setError(d.error||"Login failed");return}window.dispatchEvent(new Event("numelixa-auth-ready"));router.push(next&&next.startsWith("/")?next:"/dashboard");
  }catch{setError("Unable to contact Numelixa. Please try again.")}finally{setLoading(false)}
 }
 useEffect(()=>{if(!approval?.approvalId)return;let stopped=false;const timer=window.setInterval(async()=>{try{const d=await fetch("/api/auth/login/approval?id="+encodeURIComponent(approval.approvalId),{cache:"no-store"}).then(x=>x.json());if(stopped)return;const a=d.approval;if(a?.status==="approved"){stopped=true;window.clearInterval(timer);window.dispatchEvent(new Event("numelixa-auth-ready"));router.push(next&&next.startsWith("/")?next:"/dashboard")}else if(a?.status==="denied"||a?.status==="expired"){stopped=true;window.clearInterval(timer);setApproval(null);setError(a.status==="expired"?"The approval request expired.":"Login was not approved on your Numelixa app.")}}catch{}},1800);return()=>{stopped=true;window.clearInterval(timer)}},[approval?.approvalId]);
 if(approval)return <div className="auth-page auth-modern"><div className="auth-brand"><div className="brand-mark">N</div><span>NUMELIXA</span></div><div className="auth-intro"><span className="eyebrow">EXTRA SECURITY</span><h1>Approve your login</h1><p>Open Numelixa on your Android device and approve this browser login.</p></div><div className="form-card auth-form"><div className="security-approval-card"><b>New browser login</b><span>{approval.device||"Browser"} · {approval.city||"Location unavailable"}</span><small>Choose <b>Yes, it's me</b> in the app to continue.</small></div><div className="approval-waiting">Waiting for approval…</div><button className="secondary-btn full" onClick={()=>setApproval(null)}>Cancel</button></div></div>;
 return <div className="auth-page auth-modern"><div className="auth-brand"><Link href="/" className="brand-mark">N</Link><span>NUMELIXA</span></div><div className="auth-intro"><span className="eyebrow">WELCOME BACK</span><h1>Sign in to your workspace.</h1><p>Access your virtual numbers, live SMS, wallet and orders.</p></div><div className="auth-method-switch"><button className={method==="email"?"active":""} onClick={()=>setMethod("email")}>Email & password</button><button className={method==="phone"?"active":""} onClick={()=>setMethod("phone")}>📱 Phone OTP</button></div><div className="google-signin-section"><span>Or continue with</span><GoogleSignIn onSuccess={()=>router.push("/dashboard")}/></div>{method==="phone"?<PhoneAuth mode="login"/>:<div className="form-card auth-form"><label>Email<input value={email} onChange={x=>setEmail(x.target.value)} type="email" autoComplete="email" placeholder="you@example.com"/></label><label>Password<input value={secret} onChange={x=>setSecret(x.target.value)} type="password" autoComplete="current-password" placeholder="Your password"/></label>{error&&<div className="error-box">{error}</div>}<button className="primary-btn full" onClick={go} disabled={loading}>{loading?"Signing in…":"Sign in →"}</button><Link className="text-link" href="/forgot-password">Forgot password?</Link></div>}<p className="auth-switch">New to Numelixa? <Link href="/signup">Create your account</Link></p></div>
}